name: CI/CD Pipeline
run-name: "[${{ github.event_name }}] - ${{ github.ref_name }}: ${{ github.event.head_commit.message || github.event.pull_request.title }}"

on:
  pull_request:
    # Triggers on the creation of a PR, new commits, or reopening
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches: [main]

jobs:
  pr_setup:
    runs-on: ubuntu-latest
    outputs:
      fullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}
      semver: ${{ steps.gitversion.outputs.MajorMinorPatch }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Fetches the PR merge commit specifically
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion # This ID allows you to reference outputs later
        uses: gittools/actions/gitversion/execute@v1.1.1

      - name: Print Version to Console
        run: |
          echo "Full SemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
          echo "Major: ${{ steps.gitversion.outputs.major }}"
          echo "Minor: ${{ steps.gitversion.outputs.minor }}"
          echo "Patch: ${{ steps.gitversion.outputs.patch }}"
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.MajorMinorPatch }}"

  build:
    runs-on: ubuntu-latest
    needs: [pr_setup]
    steps:
      - name: "Beginning build..."
        run: echo "Beginning build..."      

  create_release:
    runs-on: ubuntu-latest
    needs: [pr_setup, build]
    permissions:
      contents: write
    steps:
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'  #dont create releases unless its running directly on the main branch
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.pr_setup.outputs.semver }}
          name: Release ${{ needs.pr_setup.outputs.semver }}
          draft: false
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  pr_capstone_check:
    runs-on: ubuntu-latest
    needs: [pr_setup, create_release]
    steps:
      - name: "What is this job?"
        run: echo "This job is a point of extensibility that can be enhanced to provide additional checks outside of 1st class Branch Rulesets. This can be helpful for cross-checking work item queries, QA results, etc..."
      
