name: CI/CD Pipeline
run-name: "[${{ github.event_name }}] - ${{ github.ref_name }}: ${{ github.event.head_commit.message || github.event.pull_request.title }}"

on:
  pull_request:
    # Triggers on the creation of a PR, new commits, or reopening
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      fullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}
      semver: ${{ steps.gitversion.outputs.MajorMinorPatch }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Fetches the PR merge commit specifically
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion # This ID allows you to reference outputs later
        uses: gittools/actions/gitversion/execute@v1.1.1

      - name: Print Version to Console
        run: |
          echo "Full SemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
          echo "Major: ${{ steps.gitversion.outputs.major }}"
          echo "Minor: ${{ steps.gitversion.outputs.minor }}"
          echo "Patch: ${{ steps.gitversion.outputs.patch }}"
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.MajorMinorPatch }}"

  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      # Sets up BuildKit (standard for modern Docker builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./snowflake-api
          file: ./snowflake-api/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/ctr/pysnow:latest
            ${{ steps.login-ecr.outputs.registry }}/ctr/pysnow:${{ needs.setup.outputs.semver }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
            BUILDKIT_STEP_LOG_MAX_SIZE: 10485760
            BUILDKIT_STEP_LOG_MAX_SPEED: 10485760          

      - name: Verify Build
        run: docker image ls snowflake-api   

  create_release:
    runs-on: ubuntu-latest
    needs: [setup, build]
    permissions:
      contents: write
    steps:
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'  #dont create releases unless its running directly on the main branch
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.setup.outputs.semver }}
          name: Release ${{ needs.setup.outputs.semver }}
          draft: false
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  capstone_check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [setup, create_release]
    steps:
      - name: "What is this job?"
        run: echo "This job is a point of extensibility that can be enhanced to provide additional checks outside of 1st class Branch Rulesets. This can be helpful for cross-checking work item queries, QA results, etc..."
      
